kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: COvj8Zm1XZKh0KNfntqsAS5muZYdKYjqfItRv09O0Zg=
      - identity: {}
