---
# author: semio
#
docker_old:
  - docker
  - docker-common
  - docker-selinux
  - docker-engine
  - docker.io
  - containerd
  - runc

docker_dependent_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - software-properties-common
  - bash-completion

docker_install_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

