---
# author: semio
#
docker_old:
  - docker
  - docker-common
  - docker-selinux
  - docker-engine
  - docker.io
  - containerd
  - runc

docker_dependent_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - software-properties-common
  - bash-completion

docker_install_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_data_root: /var/lib/docker
docker_registry_mirrors: ["https://yssx4sxy.mirror.aliyuncs.com/","https://1nj0zren.mirror.aliyuncs.com","https://kfwkfulq.mirror.aliyuncs.com","https://2lqq34jg.mirror.aliyuncs.com","https://pee6w651.mirror.aliyuncs.com","http://hub-mirror.c.163.com","https://docker.mirrors.ustc.edu.cn","http://f1361db2.m.daocloud.io","https://registry.docker-cn.com"]
docker_insecure_registries: ["192.168.3.125:80"]
