apiVersion: v1
kind: Endpoints
metadata:
  namespace: kube-system
  name: kube-controller-manager
  labels:
    k8s-app: kube-controller-manager
subsets:
- addresses:
{% for ip in groups['masters'] %} 
  - ip: {{ ip }}
{% endfor %}
  ports:
  - name: http-metrics
    port: 10257
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: kube-system
  name: kube-scheduler
  labels:
    k8s-app: kube-scheduler
subsets:
- addresses:
{% for ip in groups['masters'] %}
  - ip: {{ ip }}
{% endfor %}
  ports:
  - name: http-metrics
    port: 10259
    protocol: TCP
