---
# author: semio
#
- name: remove ntp
  package:
    name: ntpdate
    state: absent

- name: install chrony
  apt:
    name: chrony
    state: present
    update_cache: yes

- name: modify chrony configure
  copy:
    src: chrony.conf
    dest: /etc/chrony.conf
    mode: 0644
    backup: yes

- name: set timezone
  timezone:
    name: Asia/Shanghai

- name: ensure chronyd is active
  systemd:
    name: chronyd
    state: restarted
    enabled: yes
