---
# author: semio
#
#- import_tasks: etcd.yml

- import_tasks: apiserver.yml

- import_tasks: controller-manager.yml

- import_tasks: scheduler.yml

- import_tasks: kubelet.yml

- import_tasks: check_status.yml
