---

- name: 'Add ipnames to {{ hostnames_file }}'
  lineinfile:
    backrefs: true
    state: present
    dest: '{{ hostnames_file }}'
    regexp: '^192.'
    line: '{{ansible_all_ipv4_addresses}} {{ ansible_nodename }}'
